chapter:
  - name: Styrelsen
    contact: sytrelsen@isflemingsberg.se
    primaryRoles:
      - Sektionsordförande
      - Vice Sektionsordförande
      - JML-ansvarig
      - Studienämndens Ordförande
    roles:
      - name: Sektionsordförande
        contact: ordf@isflemingsberg.se
        members: [Emma Johansson]
      - name: Vice Sektionsordförande
        contact: vordf@isflemingsberg.se
        members: [Riff Bravo]
      - name: Ledamöter
        members: [Engla Lundin, Robin Björn, Matilda Liljegren]
      - name: JML-ansvarig
        contact: jml@isflemingsberg.se
        members: [Tuva Svanström]
      - name: Studienämndens Ordförande
        contact: sno@isflemingsberg.se
        members: [Joel Österlund]
      - name: Styrelsesekreterare
        members: [Patryk Kondratowicz]

  - name: Mottagningsgruppen
    contact: mogen@isflemingsberg.se
    primaryRoles:
      - Gudfadder
    roles:
      - name: Gudfadder
        members: [Axel Åström]
      - name: Vice Gudfadder
        members:
          [
            Anton Ljungkvist,
            Carl Fröjdendahl,
            Daniel Palitz,
            Jonatan Viel Lamare,
            Þráinn Þórisson,
          ]
      - name: Mottagningskassör
        members: [Simon Ulin]

  - name: Talsmanspresidiet
    contact: talman@isflemingsberg.se
      - Talman
    roles:
      - name: Talman
        members: [Axel Åström]
      - name: Talmanssekreterare
        members: [Carl Fröjdendahl]

  - name: Studerande skyddsombud
    roles:
      - members: [Jesper Fleetwood]

  - name: Revisorer
    roles:
      - members: [William Ramberg]

  - name: Kårfullmäktige
    roles:
      - name: Kårfullmäktige Ledamot
        members: [Emma Johansson]
      - name: Kårfullmäktige Suppleant
        members: [Julia Lofland Gustafsson]

  - name: Qlubbmästeriet
    contact: qm@isflemingsberg.se
    primaryRoles:
      - Qlubbmästare
    roles:
      - name: Qlubbmästare
        members: ["-"]
      - name: Vice Qlubbmästare
        members: [Erik Moreno]
      - name: Vinstmästare
        members: ["-"]

  - name: Företagsgruppen
    contact: fg@isflemingsberg.se
    primaryRoles:
      - Företagsgruppens Ordförande
    roles:
      - name: Företagsgruppens Ordförande
        members: [Linus Hasselkvist]
      - name: Företagsgruppens Vice Ordförande
        members: [Nina]

  - name: Valberedningen
    contact: valberedning@isflemingsberg.se
    primaryRoles:
      - Valberedningens Ordförande
    roles:
      - name: Valberedningens Ordförande
        members: [Johan Gripenhall]
      # - name: Valberedningens Vice Ordförande
      # members: []

  - name: Idrottsgruppen
    contact: igor@isflemingsberg.se
    roles:
      - name: Idrottsgruppens Ordförande
        members: [Sardor Jurayev]

  - name: Infogruppen
    contact: info@isflemingsberg.se
    roles:
      - name: Infogruppens Ordförande
        members: [Engla Lundin]

  - name: Spruppen
    contact: spruppen@isflemingsberg.se
    roles:
      - name: SPRUPPÖverste
        members: [Daniel Palitz]
      - name: SPRUPPÖversteLöjtnant
        members: [Said Burhan]

  - name: Slurpenredaktionen
    roles:
      - name: Chefredaktör
        contact: tuva@isflemingsberg.se
        members: [Tuva Svanström]

  - name: Utbytesnämnden
    roles:
      - name: Utbytesnämndens Ordförande
        contact: adam@isflemingsberg.se
        members: [Elias Mailosson]

  - name: Lokalnämnden
    contact: lokal@isflemingsberg.se
    roles:
      - name: Lokalnämndens Ordförande
        members: [Elias Mailosson]
